# Generated by Django 3.1 on 2022-02-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_auto_20220223_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('IN PROCESSING', 'in processing'), ('AWAITING_PAYMENT', 'awaiting payment'), ('PAID', 'paid'), ('READY', 'ready'), ('CANCELLED', 'cancelled'), ('FINISHED', 'finished')], default='CREATED', max_length=20, verbose_name="order's status"),
        ),
    ]
