# Generated by Django 3.1 on 2022-02-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0004_auto_20220201_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('id',)},
        ),
    ]
